### ISSUE TITLE
Allow `mut` keyword in `boot_contract` prefixed endpoints

### ISSUE THREAD

**Issue by Kayanski** [AbstractSDK/cw-orchestrator#94]
The change introduced by #77, doesn't allow endpoint to declare their variable using modifiers such as `mut`.
The following error appears : 
```
error[E0561]: patterns aren't allowed in function pointer types
```

## Origin
This issue comes from the macro saving the following function as a function pointer that doesn't allow such patterns. 

## Temporary fix

To fix this issue, simple replace

```
#[cfg_attr(not(feature = "library"), entry_point)]
#[cfg_attr(feature="boot", boot_contract)]
pub fn instantiate(
    mut deps: DepsMut,
    env: Env,
    info: MessageInfo,
    msg: InstantiateMsg,
) -> StdResult<Response> {
    ...
```

by 

```
#[cfg_attr(not(feature = "library"), entry_point)]
#[cfg_attr(feature="boot", boot_contract)]
pub fn instantiate(
    deps: DepsMut,
    env: Env,
    info: MessageInfo,
    msg: InstantiateMsg,
) -> StdResult<Response> {
    let mut deps = deps;
    ...
```

## Fix idea
We should remove the patterns on the arguments when saving the function pointer in a variable

**Comment by Kayanski** [comment]
Resolved in https://github.com/AbstractSDK/cw-orchestrator/pull/104
